# Generated by Django 3.2 on 2023-07-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='photographer_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
