# Generated by Django 3.2 on 2023-08-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_alter_appointment_appointment_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_total_price',
            field=models.CharField(max_length=200),
        ),
    ]
