# Generated by Django 3.2 on 2023-08-10 08:20

import client.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_alter_appointment_appointment_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('uploads', models.ImageField(default=None, null=True, upload_to=client.models.wrapperer)),
                ('appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.appointment')),
            ],
            options={
                'db_table': 'Uploads',
            },
        ),
    ]
