# Generated by Django 3.2 on 2023-08-08 10:17

from django.db import migrations, models
import photographer.models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to=photographer.models.wrapper),
        ),
    ]
