# Generated by Django 3.2 on 2023-08-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0002_alter_photographer_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='canBeRequested',
            field=models.BooleanField(default=True),
        ),
    ]
